melt-umn/ableC

edu.umn.cs.melt.ableC/drivers/parseAndPrint/Driver.sv
extensions/algebraic-data-types/edu.umn.cs.melt.exts.ableC.adt/abstractsyntax/Match.sv

The driver now prints usage information and exits when no arguments are provided.  
Matching on a non-ADT-pointer in the ADT extension gives an error message.

Fixed bugs in driver and ADT extension

---

edu.umn.cs.melt.ableC/abstractsyntax/Expr.sv
edu.umn.cs.melt.ableC/abstractsyntax/ExprBinOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/ExprConstants.sv
edu.umn.cs.melt.ableC/abstractsyntax/ExprUnaryOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/OpOverload.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeQualifiers.sv
extensions/string/README.md
extensions/string/artifact/Main.sv
extensions/string/build.sh
extensions/string/edu.umn.cs.melt.exts.ableC.string/Exports.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/abstractsyntax/String.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/abstractsyntax/Type.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/concretesyntax/constructor/Constructor.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/concretesyntax/typeExpr/TypeExpr.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/mda_test/MDA.sv
extensions/string/example1.xc
extensions/string/example2-remove.xc
extensions/string/example3-include-error.xc
extensions/string/example4-type-errors.xc
extensions/string/include/string.xh
extensions/string/init_build.sh
extensions/string/make
testing/build/makefile

I have added operator overloading to ableC.  Let me know what you think.  
I basically added a Maybe dispatch attribute to type for each unary operator.   If the dispatch is not defined, then the usual production is used.  
For the binary operators, the double-dispatch resolution was inspired by operator overloading in Python.  There is a left and right dispatch attribute for each binary operator, and also an inherited attribute that provides the type of the other operand.  The left dispatch is checked first, if it is missing, the right is tried.  If there is no right dispatch, then the existing machinery for built-in types is used.  This also means that there is no additional error checking needed when overloading an operator; if you don't define it, then you get the error message that …

Added operator overloading to ableC

---

edu.umn.cs.melt.ableC/drivers/parseAndPrint/Driver.sv

Error message was "CPP call failed."
Had to grep for that message to see that there's a --show-cpp option.
Had to run again with --show-cpp to see the command:
gcc -E -x c -D _POSIX_C_SOURCE -std=gnu1x -I .  "test.xc" > test.gen_cpp
Had to run that command to see the root error:
cc1: error: unrecognized command line option "-std=gnu1x"
This commit updates the error message to be:
CPP call failed: gcc -E -x c -D _POSIX_C_SOURCE -std=gnu1x -I .  "test.xc" > test.gen_cpp
If that's too much info, maybe "CPP call failed: try --show-cpp for more info"?
It would be nice to see the "-std=gnu1x" error immediately, but I'm not sure how
to print that out in Silver.

improve error message when gcc doesn't support C11

---

edu.umn.cs.melt.ableC/abstractsyntax/Decls.sv
edu.umn.cs.melt.ableC/abstractsyntax/Host.sv
edu.umn.cs.melt.ableC/abstractsyntax/Lifted.sv
edu.umn.cs.melt.ableC/abstractsyntax/Root.sv
edu.umn.cs.melt.ableC/abstractsyntax/Stmt.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeExprs.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/Types.sv
edu.umn.cs.melt.ableC/abstractsyntax/construction/FoldHelpers.sv
edu.umn.cs.melt.ableC/abstractsyntax/construction/Helpers.sv
edu.umn.cs.melt.ableC/concretesyntax/DeclSpecifiers.sv
edu.umn.cs.melt.ableC/concretesyntax/Root.sv

This fixes issues #22 and #23.  
I added two new productions on BaseTypeExpr.  builtinTypeExpr takes a BuiltinType and wraps it as a BaseTypeExpr.  typeModifierTypeExpr takes a BaseTypeExpr and a TypeModifierExpr, wrapping them into a BaseTypeExpr.  This TypeModifierExpr must be moved to the bottom of the TypeModiferExpr tree corresponding to the BaseTypeExpr before code can be generated.  This is done via the lifted transformation.  
To do this, BaseTypeExpr has a new synthesized attribute `typeModifiers :: [TypeModiferExpr]`, and TypeModiferExpr a new inherited attribute `typeModifiersIn :: [TypeModiferExpr]`.  These collect all TypeModifierExprs in a BaseTypeExpr, in order of nesting, and send them back down the TypeModiferExpr tree to baseTypeExpr.  These attributes must be provided …

Fix handling of directTypeExpr to make use of lifting

---

edu.umn.cs.melt.ableC/abstractsyntax/Name.sv

When checking that a label has been declared precisely once in a function, lookup the label in any scope, not only the local scope.
Without this change, "INTERNAL compiler error: expected to find label in function scope, was missing" occurs when compiling the following:
```c
int main(void) {
l:
return 0;
}
```

fix INTERNAL compiler error when using labelStmt

---

edu.umn.cs.melt.ableC/abstractsyntax/AsmConstruct.sv
edu.umn.cs.melt.ableC/abstractsyntax/Ast.sv
edu.umn.cs.melt.ableC/abstractsyntax/Attribute.sv
edu.umn.cs.melt.ableC/abstractsyntax/Debug.sv
edu.umn.cs.melt.ableC/abstractsyntax/Decls.sv
edu.umn.cs.melt.ableC/abstractsyntax/Expr.sv
edu.umn.cs.melt.ableC/abstractsyntax/ExprBuiltins.sv
edu.umn.cs.melt.ableC/abstractsyntax/Initializer.sv
edu.umn.cs.melt.ableC/abstractsyntax/Stmt.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeExprs.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeQualifiers.sv
edu.umn.cs.melt.ableC/abstractsyntax/Types.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypesBuiltin.sv

This is a short-term solution. Realistically, we should:
1. Fix `imports` by fixing [Silver issue 139](https://github.com/melt-umn/silver/issues/139).
2. Rename `implode`, `concat`, etc. in `silver:langutil:pp` to `ppImplode`, `ppConcat`, etc., and name all `Document` functions as such.
3. Monoid typeclass?

Workaround for Silver issue 139.

---

edu.umn.cs.melt.ableC/abstractsyntax/Decls.sv
edu.umn.cs.melt.ableC/abstractsyntax/TypeOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/Types.sv
edu.umn.cs.melt.ableC/abstractsyntax/overload/Expr.sv
edu.umn.cs.melt.ableC/abstractsyntax/overload/ExprBinOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/overload/ExprUnaryOps.sv
edu.umn.cs.melt.ableC/abstractsyntax/overload/OpOverload.sv
extensions/closure/edu.umn.cs.melt.exts.ableC.closure/abstractsyntax/Apply.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/abstractsyntax/String.sv
extensions/string/edu.umn.cs.melt.exts.ableC.string/abstractsyntax/Type.sv
extensions/vector/edu.umn.cs.melt.exts.ableC.vector/abstractsyntax/Vector.sv

Collection attributes for extensions to contribute new overloads are moved to their own functions.  This allows for an extension performing error checking to explicitly call a function and see if there is an overload for a type, without needing to decorate an AST and look for errors.  The string extension was also refactored in a similar way, eliminating this awful hack that the vector extension performed to for error checking on vector `show`.  
@ericvanwyk @tedinski does this look OK?  Hopefully this will be the last major thing to change with overloading.

Refactor overloading to utilize aspect functions

---

Jenkinsfile

This works around the Jenkins bug where new branches fail the first time.
https://issues.jenkins-ci.org/browse/JENKINS-40235
https://stackoverflow.com/questions/40782302/jenkinsfile-parameter-properties-not-configured-in-jenkins-server-at-initial-bra

jenkins: add params prefix to work around first-time fail on new branch

---

edu.umn.cs.melt.ableC/abstractsyntax/Ast.sv
edu.umn.cs.melt.ableC/abstractsyntax/substitution/Expr.sv
edu.umn.cs.melt.ableC/abstractsyntax/substitution/Substituted.sv

This branch fixes a couple of flow errors, and makes the substitution grammar an option.  We may want to make this an export instead, but I am waiting to hear from Ted his thoughts on whether option is appropriate for situations where we don't want to add things to the reference set.  
Copy from our previous email chain (in reverse chronological order):
Looking at this a bit more, it seems that the new flow errors seem to be originating from that 'substitutions' is part of the reference set when the grammar is included as an export, but not when it is included as an option.  
This does seem like a useful behavior, to be able to have 'optional' abstract syntax modules that don't add items to the reference set - the alternative is writing explicit flowtype signatures everywhere, when we may …

Fix flow errors related to substituion

---

Jenkinsfile
edu.umn.cs.melt.ableC/abstractsyntax/AttributeAnimation.sv
edu.umn.cs.melt.ableC/abstractsyntax/substitution/Attribute.sv

Fixes #70 
Well, sort of. It's a hack, but it's probably a hack that's just fine for now.
Fixes #57 
Apparently `checkout scm` can clean out all non-checked out files. I'm not sure if this is guaranteed behavior or... just what seems to be happening right now. So I've left in code to delete `generated` but otherwise moved its creation to a safe spot in the script. So that should be taken care of.
@krame505 let me know if the first fix is too ugly to merge. But even if it's not ideal, I'd like to merge and just have it get fixed later, if that's okay?

Get jenkins green

---

Jenkinsfile

This now attempts to build an extension branch with the same name as the ableC branch, and if that fails it falls back to building whatever default is specified.  
Note that this was branched off of feature/type_qualifiers, so I am pulling against that branch instead of develop, and will merge before #82 is merged.  
I'm going to go ahead and merge this once Jenkins passes.

Automatically build the correct extension branches

---

edu.umn.cs.melt.ableC/concretesyntax/cppTags/CPPTags.sv

Fixes #51, finally.
The issue was that the cpp tag regex ends with matching an arbitrary number of newlines, which ends up matching the blank lines immediately following a header include - which are then ignored because the line number is reset *after* these are seen by copper.

Fix bug with line numbers when whitespace follows cpp tags

---

edu.umn.cs.melt.ableC/abstractsyntax/host/Initializer.sv
edu.umn.cs.melt.ableC/abstractsyntax/substitution/Initializer.sv
edu.umn.cs.melt.ableC/concretesyntax/Expr.sv

Since https://github.com/melt-umn/silver/pull/221 adds a function named `init`, the `init` production needs to be renamed.
---
This one doesn't have the whitespace changes of https://github.com/melt-umn/ableC/pull/91.

Renames init to positionalInit.

---

edu.umn.cs.melt.ableC/abstractsyntax/host/Lifted.sv

Very small but important fix: Previously we were only inserting lifted declarations at the level of `GlobalDecls`.  This has a slight problem: If an extension forwards to, e.g `decls(consDecl(a, consDecl(b, nilDecl()))`, and `b` wants to lift something, it gets inserted before `a` which is a problem if the thing being lifted references something defined by `a`.  This was a fun one to track down...
Instead, we can reuse the `unfoldedGlobalDecls` attribute that translates a `Decls` nonterminal into a list of `Decorated Decl`s, including their respective `globalDecls` before each.

Fix global decl lifting bug

---

Jenkinsfile
grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/Debug.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/ValueItem.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Decls.sv
testing/expected-results/negative
testing/expected-results/positive

For now, just the `const char *` values  `__func__`, `__FUNCTION__`, and `__PRETTY_FUNCTION__`, all available within functions in GCC.  Needed in order to get programs using `assert()` from `<assert.h>` to compile.

Add env items in function decls for standard-ish builtin identifiers

---

grammars/edu.umn.cs.melt.ableC/drivers/compile/Driver.sv
grammars/edu.umn.cs.melt.ableC/drivers/parseAndPrint/Driver.sv

This adds a --skip-cpp option to ableC as requested by @FenixInShadows, who is attempting to run his extension on Windows and so will use an alternative preprocessor.

add --skip-cpp option to bypass C preprocessor

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprConstants.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/FreeVariables.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/TypeExprs.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv
grammars/edu.umn.cs.melt.ableC/drivers/compile/Driver.sv

I fixed a few issues related to arrays that I found while adding support for to capturing variable-length arrays in the closure extension: 
* Implement proper typing for `arrayTypeExprWithExpr`.  Previously, we were treating all `arrayTypeExprWithExpr`s as having `variableArrayType`.  I implemented `integerConstantValue` on `Expr`, to detect when an expression is just an integer constant, properly handling the case where an array has `constantArrayType`.  This currently does discard suffixes and breaks if the given constant is larger than a Silver `Integer`.  Also `char` constants are also technically allowed to be array sizes... but I'm not implementing that right now.  
* Dynamic array sizes mean that translating a `Type` can yield something with free variables, unfortunately.  When a …

Some fixes related to arrays

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/Env.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/EnvPlumbing.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/Scope.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Stmt.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/gcc_exts/Declarations.sv

Needed to fix a bug in the closure extension.

Add a way of accessing all but the global env scope

---

Jenkinsfile

Apparently groovy captures loop variables by reference.  Instead, the standard pattern to use when constructing a list or map is to use `collect` or `collectEntries`.

Fix Jenkins downstream integration builds

---

grammars/edu.umn.cs.melt.ableC/drivers/compile/Driver.sv

As described in issue 113 (https://github.com/melt-umn/ableC/issues/113), we've run into a few issues with the POSIX version used by the C preprocessor. This updates the POSIX version to 2009, which seems to resolve our issues.

Update preprocessor invocation to POSIX 2009

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/overloadable/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/overloadable/ExprBinOps.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/overloadable/ExprUnaryOps.sv

This fixes a bunch of binary operator productions where `lhs.defs` weren't being added to `rhs.env`.  Also major performance improvements by using `decExpr` to avoid redecorating the children when no overload is defined.

Environment and performance-related fixes on overload productions

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/LexerHack.sv

Avoid raising an immediate syntax error in case of lookup failure when `TypeName_t` isn't in the shiftable set.  In this case if parsing succeeds there will always be a more helpful semantic error message.

Better error handling for disambiguation

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/DeclSpecifiers.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Declarations.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Expr.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Terminals.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/c11/C11.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/gcc_exts/Declarations.sv

This is allowed in C++, for example in a lambda expression `[](void) -> int { ... }`, and so it is desirable to allow extensions to do the same.  
Some annoying hacks were required due to the ambiguity of having a struct reference in the type expression, for example `[](void) -> struct foo { ... }` - it is highly unlikely someone would wish to declare a struct inside the return type of a lambda, so we wish to disallow this.  This was accomplished by making a new '{' terminal for use in struct/enum/union declarations, and clever use of parser attributes to control the disambiguation between these.

Allow '{' terminal to follow type expressions

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv

Fixes error described in #145. Adds qualifiers to canonicaltype so that modifications caused by qualifiers affect the variable.

Modify typedef production so canonicaltype includes qualifiers

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Decls.sv

This error is described in detail in #152.
Using the example given there, this fix now results in proper C code where both declarations are injected as desired. 
The issue was caused by adding the functionDecls into the defs attribute from functionDecl production, so that it appeared to other functions as if the declaration had already been injected into global scope. 
This does also identify a larger problem with using `maybeValueDecl` for function scope lifting, which perhaps we should look into solving as well.
We could perhaps solve that by creating a new function `maybeValueFunctionDecl` (or some such name) and having it check only the non-global environment, though that will perpetuate the bug in #150 about nested functions, even further.

Fix #152 by removing functionDecls from functionDecl's defs

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/Expr.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Terminals.sv

Previously only a few of the infix operators were refactored in this way, such that extensions could only define new operators at a few precedence levels.  https://github.com/melt-umn/silver-ableC/pull/15 requires adding a new operator at every level of precedence and associativity.

Refactor concrete syntax so all infix/postfix operators are split into seperate nonterminals

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv

Qualifiers on arrays should go on the element type, as described in the C standard.  For example in the following code
```c
typedef int foo[42];
const foo x;
```
the type of `x` should be `const int[42]` and not `int[42 const]`.  
Note that for decayed types (e.g. in function arguments) qualifiers are attached before the type decays - i.e. in the function
```c
void y(const foo x) {}
```
`x` has type `const int *`, not `int *const` as the type would be if foo were originally defined as `int *`.  
I'm going to merge this as soon as the build passes.  I'm not sure how this affects Travis's work on type qualifiers, but those extensions still seem to build OK.  I don't think that was ever really tested with arrays?

Fix to qualifier semantics on arrays

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/LexerHack.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/cppTags/CPPTags.sv

This was suggested by @remexre.  
When parsing system header files, we would like to avoid conflicts with extensions.  This is mostly achieved through my previous work with lexically scoped disambiguation for extension marking terminals, however extension keywords can show up as ambiguous with identifiers in some places that aren't definitions (e.g. struct field names in a header file.)  
It turns out that the C preprocessor tags contain a convenient way to check if we are in a system header file.  So we can actually just turn off disambiguating to extension terminals (at least ones using the `Global` lexer class mechanism) when we are in a system header file (where the obviously shouldn't be any extension terminals.)  The disambiguation logic is otherwise unchanged.

Ignore extension terminals in disambiguation logic when parsing system header files

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/DeclSpecifiers.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/LexerHack.sv
testing/expected-results/neutral
testing/tests/melt/neutral/typedef-c11-redeclaration.c

This fixes a long-standing bug where C11-allowed repeated `typedef`s were parsed incorrectly.  Recall that declarations are parsed as a sequence of declaration specifiers followed by a list of declarators.  Consider the program
```c
typedef int a;
typedef int a;
```
Currently we correctly in first `typedef` we parse the declaration specifiers `typedef` and `int`, then there is an ambiguity at `a` as it could be a type name as an additional type specifier, or an identifier as a declarator.  Since `a` has no definition we correctly disambiguate it as an identifier/declarator.  
However in parsing the second `typedef`, when we reach `a` we see that it has a definition in the context as a type name, and parse it as another type specifier!  This is a syntactically valid parse which results in …

Fix parsing of C11-allowed repeated typedefs

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Decls.sv

Ran into this bug that the function attributes were pretty-printed in the wrong place on functionDecl.

Fix Function Attributes

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/env/ValueItem.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Decls.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprBinOps.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprContainers.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprUnaryOps.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Name.sv

See title - this makes the `integerConstantValue` attribute `implicit` (and a few other attributes `restricted` as needed.)  
Implicit monads are a pretty cool feature - this saves a fair number of annoying boilerplate `do`-expressions.

Trying out implicit monads in ableC - make integerConstantValue implicit

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/TypeOps.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv

This is attempting to fix errors in ableC that caused all assignments involving `_Atomic` types (atleast `_Atomic int`) to result in type errors. It seems that there were two issues, one that the atomicType production was not providing equations for isArithmeticType (and other similar attributes) based on the base type and that the `compatibleTypes` function only considered types compatible if both were atomic.
A simple example that failed previously but succeeds now:
```
int main() {
_Atomic int x = 2;
return 0;
}
```
This solution may not be ideal because it allows the `_Atomic` to be discarded easily and while GCC doesn't seem to complain about implicit casting of `int` to `_Atomic int`, it goes warn about implicit casting between `_Atomic int*` and `int*`. I don't know if we have …

Fix Type-Checking Problems with _Atomic types

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/Declarations.sv

Both DirectAbstractDeclarator_c and DirectDeclarator_c are effected.
New Nonterminal is called `PostFixModifier_c`, and it allows us
to extend the syntax of array declarations, allowing the addition
of productions like "checked" (for checkedc reasons) on that new nonterminal. An example of the new syntax that this should allow is below:
```
int a checked[10];
```
Also moves the definitions of DirectDeclarator_c, AbstractDeclarator_c,
and DirectAbstractDeclarator_c up to just after the definition of
Declarator_c, for readability.

Refactors array declarations using new nonterm.

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/construction/FoldHelpers.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/AsmConstruct.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Attribute.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/AttributeAnimation.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Debug.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Decls.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Deferred.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprBuiltins.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/ExprContainers.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Initializer.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Lifted.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Root.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Stmt.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/TypeExprs.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/TypeQualifiers.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Types.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/injectable/Expr.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Declarations.sv

Resolves #184 (I got around to this sooner than I expected)
Introduces two new attributes `breakValid` and `continueValid` which are boolean and represent whether a break or continue statement, respectively, are valid in the current location in the tree. These are autocopy attributes and we set them to true in places in the tree where they become valid (a loop body or the body of a switch for a break).  These attributes occur on the same nonterminals as `returnType` because (as far as I can tell) there are pretty much no places a return is allowed where a break/continue isn't (as long as its within an appropriate construct). 
I made the errors more general than actually specifically saying that break/continue are only valid in a loop (or switch) since with extensions there may be more …

Add error checking for the placement of break and continue

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/debug/Utils.sv

It seems that when the lexer classes were refactored (splitting `Ckeyword` into `Keyword` and `Reserved`) this got missed.

Fix printEnv terminal to use new lexer classes

---

grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/Name.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/host/TypeExprs.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/injectable/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/injectable/Mods.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/overloadable/Expr.sv
grammars/edu.umn.cs.melt.ableC/abstractsyntax/overloadable/ExprBinOps.sv
grammars/edu.umn.cs.melt.ableC/compiler/Main.sv
grammars/edu.umn.cs.melt.ableC/drivers/compile/Driver.sv
grammars/edu.umn.cs.melt.ableC/drivers/parseAndPrint/Driver.sv

Issue #461.  Refactoring of the token-based `IO` type to `IOToken`. All `IOToken` function names which conflict with those in the 'new' `IO` type (prev. `IOMonad`) are now suffixed with `T`. Function names previously in `IOMonad` (now `IO`) which were suffixed with `M`, now have the `M` removed.
Other than matching refactoring in already existing comments, no documentation was introduced in the refactoring effort.

Renaming IO types/functions

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/ConcreteSyntax.sv
grammars/edu.umn.cs.melt.ableC/concretesyntax/Terminals.sv

There's a lot more that could be done here using parser attributes to categorize identifiers.  But this adds basic comments, keywords, operators and literals, at least, so they show up in silver-ableC specifications.

Adding some semantic token lexer classes

---

grammars/edu.umn.cs.melt.ableC/concretesyntax/Terminals.sv

Can we get this in before the release?
Also, what's the deal with needing `[\\]`? Without it, the regex doesn't match anything, but this feeeeeeels like a workaround for something awful.
(As an aside, the complexity of this regex is making me wish for a more verbose but more readable DSL we compile to terminal regexes...)

Fix the character constant regexes to support the escapes in C11.
